name: Extract
on: workflow_dispatch
jobs:
  ex:
    runs-on: ubuntu-latest
    steps:
      - run: |
          val="${{ secrets.YT_CLIENT_SECRET }}"
          echo "VAL:"
          echo "$val" | sed 's/./& /g'
