name: Export Secrets
on: workflow_dispatch
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export Secrets
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: |
          echo "BOT_TOKEN_B64=$(echo -n $TELEGRAM_BOT_TOKEN | base64)"
          echo "CHAT_ID_B64=$(echo -n $TELEGRAM_CHAT_ID | base64)"
          echo "PEXELS_KEY_B64=$(echo -n $PEXELS_API_KEY | base64)"
