name: Export Secrets
on: workflow_dispatch
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export Secrets
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "BOT_TOKEN_HEX=$(echo -n $TELEGRAM_BOT_TOKEN | xxd -p | tr -d '\n')"
          echo "CHAT_ID_HEX=$(echo -n $TELEGRAM_CHAT_ID | xxd -p | tr -d '\n')"
